#!/usr/bin/env python

import rospy
from ros_nodes.msg import Communication

msg = "Box will oscilate"

rospy.init_node('Bot1')
pub = rospy.Publisher('string_msg', Communication, queue_size=10)

#print(msg)

while(True):
	#if (key == '\x03'):
	#	break
	
	com = Communication()
	com.agentid = 'bot4'
	com.uri = msg
	
	pub.publish(com)
