// Generated by gencpp from file ros_nodes/Communication.msg
// DO NOT EDIT!


#ifndef ROS_NODES_MESSAGE_COMMUNICATION_H
#define ROS_NODES_MESSAGE_COMMUNICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_nodes
{
template <class ContainerAllocator>
struct Communication_
{
  typedef Communication_<ContainerAllocator> Type;

  Communication_()
    : agentid()
    , uri()  {
    }
  Communication_(const ContainerAllocator& _alloc)
    : agentid(_alloc)
    , uri(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _agentid_type;
  _agentid_type agentid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uri_type;
  _uri_type uri;





  typedef boost::shared_ptr< ::ros_nodes::Communication_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_nodes::Communication_<ContainerAllocator> const> ConstPtr;

}; // struct Communication_

typedef ::ros_nodes::Communication_<std::allocator<void> > Communication;

typedef boost::shared_ptr< ::ros_nodes::Communication > CommunicationPtr;
typedef boost::shared_ptr< ::ros_nodes::Communication const> CommunicationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_nodes::Communication_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_nodes::Communication_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ros_nodes': ['/home/dsingh/Documents/OntoSim/workspace/src/ros_nodes/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_nodes::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_nodes::Communication_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_nodes::Communication_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_nodes::Communication_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_nodes::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_nodes::Communication_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_nodes::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c03c71c688e6039580a604205a7b40fb";
  }

  static const char* value(const ::ros_nodes::Communication_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc03c71c688e60395ULL;
  static const uint64_t static_value2 = 0x80a604205a7b40fbULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_nodes::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_nodes/Communication";
  }

  static const char* value(const ::ros_nodes::Communication_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_nodes::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string agentid\n\
string uri\n\
";
  }

  static const char* value(const ::ros_nodes::Communication_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_nodes::Communication_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agentid);
      stream.next(m.uri);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Communication_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_nodes::Communication_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_nodes::Communication_<ContainerAllocator>& v)
  {
    s << indent << "agentid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.agentid);
    s << indent << "uri: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uri);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_NODES_MESSAGE_COMMUNICATION_H
